app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from app import views

app_name = 'app'  # Add this line to specify the app namespace


urlpatterns = [
    path("",views.home, name='home'),
    path('create-room/', views.create_room, name='create_room'),
    path('join-room/', views.join_room, name='join_room'),
    path('joined-rooms/',views.joined_rooms,name='joined_rooms'),
    path('leave-room/<int:room_id>/', views.leave_room, name='leave_room'),
    path('created-rooms/', views.created_rooms, name='created_rooms'),
    path('room/<int:room_id>/delete/', views.delete_room, name='delete_room'),

    path('room/<int:room_id>/quizzes', views.room_quizzes, name='room_quizzes'),
    path('room/<int:room_id>/assignments/', views.room_assignments, name='room_assignments'),
    path('room/<int:room_id>/exams/', views.room_exams, name='room_exams'),

    path('quiz/<int:quiz_id>/submit/', views.room_quizzes, name='submit_quiz'),
    path('assignment/<int:assignment_id>/submit/', views.room_assignments, name='submit_assignment'),
    path('exam/<int:exam_id>/submit/', views.room_exams, name='submit_exam'),
    
    path('submissions/quizzes/<int:quiz_id>/', views.submitted_quizzes, name='submitted_quizzes'),
    path('submissions/assignments/<int:assignment_id>/', views.submitted_assignments, name='submitted_assignments'),
    path('submissions/exams/<int:exam_id>/', views.submitted_exams, name='submitted_exams'),


    path('update_submission_marks/<int:quiz_id>/', views.update_quiz_submission_marks, name='update_quiz_submission_marks'),
    path('update_assignment_submission_marks/<int:assignment_id>/', views.update_assignment_submission_marks, name='update_assignment_submission_marks'),
    path('update_exam_submission_marks/<int:exam_id>/', views.update_exam_submission_marks, name='update_exam_submission_marks'),
    
    path('check-submission/', views.check_submission, name='check_submission'),

    path('kick_participant/<int:room_id>/<int:user_id>/', views.kick_participant, name='kick_participant'),
    path('room/<int:room_id>/participants/', views.load_participants, name='load_participants'),


    path('student-analytics/', views.student_analytics, name='student_analytics'),
    path('teacher-analytics/', views.teacher_analytics, name='teacher_analytics'),

    path('room_detail/<int:room_id>/', views.room_detail, name='room_detail'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('room/<int:room_id>/join-requests/', views.join_requests, name='join_requests'),
    path('accept-join-request/<int:room_id>/<int:user_id>/', views.accept_join_request, name='accept_join_request'),
    path('reject-join-request/<int:room_id>/<int:user_id>/', views.reject_join_request, name='reject_join_request'),
    path('upload-book/', views.upload_book, name='upload_book'),
    path('book-list/', views.book_list, name='book_list'),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('query-form/', views.process_query1, name='query_form'),
    path('save-pdf/', views.save_pdf, name='save_pdf'),
    path('created_docs/', views.created_docs, name='created_docs'),
    path('delete_document/<int:doc_id>/', views.delete_document, name='delete_document'),

    path('help/',views.help, name='help'),


]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fyp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('', include('app.urls', namespace='app')),  # Include 'app/urls.py' with the namespace taa kay hum login k bad redirect krskyn
]

app/forms.py
from django import forms
from .models import Room , Book 


class RoomCreationForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['name']
        labels = {
            'name': 'Room Name',
        }

class JoinRoomForm(forms.Form):
    room_name = forms.CharField(max_length=100, label='Room Name')
    pass_key = forms.CharField(max_length=100, label='Pass Key')


class BookUploadForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'upload']


from .models import Quiz, Assignment, Exam, QuizSubmission, AssignmentSubmission, ExamSubmission,SavedDocument



from django.core.exceptions import ValidationError
import re

class QuizForm(forms.ModelForm):
    end_time = forms.CharField(label='End Time', required=True)

    class Meta:
        model = Quiz
        fields = ['title', 'file', 'total_marks', 'end_time']
    
    def __init__(self, *args, user=None, **kwargs):
        super(QuizForm, self).__init__(*args, **kwargs)
        self.fields['file'].queryset = SavedDocument.objects.filter(teacher=user,d_type='quiz')

    def clean_end_time(self):
        end_time = self.cleaned_data['end_time']

        # Regular expression pattern to match the desired time format '11:00 AM'
        time_pattern = re.compile(r'^\d{1,2}:\d{2} (AM|PM)$')

        # Validate the format
        if not time_pattern.match(end_time):
            raise ValidationError("Invalid time format. Please enter time in 'HH:MM AM/PM' format.")

        return end_time
    
class AssignmentForm(forms.ModelForm):
    end_time = forms.CharField(label='End Time', required=True)
    class Meta:
        model = Assignment
        fields = ['title', 'file', 'total_marks', 'end_time']

    def __init__(self, *args, user=None, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        self.fields['file'].queryset = SavedDocument.objects.filter(teacher=user,d_type='assignment')


    def clean_end_time(self):
        end_time = self.cleaned_data['end_time']

        # Regular expression pattern to match the desired time format '11:00 AM'
        time_pattern = re.compile(r'^\d{1,2}:\d{2} (AM|PM)$')

        # Validate the format
        if not time_pattern.match(end_time):
            raise ValidationError("Invalid time format. Please enter time in 'HH:MM AM/PM' format.")

        return end_time
    
class ExamForm(forms.ModelForm):
    end_time = forms.CharField(label='End Time', required=True)

    class Meta:
        model = Exam
        fields = ['title', 'file', 'total_marks', 'end_time']

    def __init__(self, *args, user=None, **kwargs):
        super(ExamForm, self).__init__(*args, **kwargs)
        self.fields['file'].queryset = SavedDocument.objects.filter(teacher=user,d_type='exam')

    def clean_end_time(self):
        end_time = self.cleaned_data['end_time']

        # Regular expression pattern to match the desired time format '11:00 AM'
        time_pattern = re.compile(r'^\d{1,2}:\d{2} (AM|PM)$')

        # Validate the format
        if not time_pattern.match(end_time):
            raise ValidationError("Invalid time format. Please enter time in 'HH:MM AM/PM' format.")

        return end_time
    

class QuizSubmissionForm(forms.ModelForm):
    class Meta:
        model = QuizSubmission
        fields = ['submission']

class AssignmentSubmissionForm(forms.ModelForm):
    class Meta:
        model = AssignmentSubmission
        fields = ['submission']

class ExamSubmissionForm(forms.ModelForm):
    class Meta:
        model = ExamSubmission
        fields = ['submission']

app/templates/app/room/assignment_submissions.html
<!-- app/room/assignment_submissions.html -->
<div id="assignment-result-container"></div>

<div class="assignments-container">
    <h2>Submissions for <b>{{ assignment.title }}</b></h2>
    {% if submissions %}
        <form method="post" action="{% url 'app:update_assignment_submission_marks' assignment_id=assignment.id %}">
            {% csrf_token %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>Marks</th>
                        <th>Submitted At</th>
                        <th>Action</th>
                        <th>AI Marks</th>
                        <th>Submission</th>
                    </tr>
                </thead>
                <tbody>
                    {% for submission in submissions %}
                        <tr>
                            <td> {% load static %}
                                {% if submission.student.profile_picture %} 
                                <img style="border-radius: 50%;" src="http://127.0.0.1:8000/{{ submission.student.profile_picture }}" alt="Profile Picture">
                                 {% else %}
                               <!-- Default profile picture if user doesn't have one --> <img style="border-radius: 50%;"
                                 src="{% static 'app/default.jpg' %}" alt="">
                                  {% endif %}
                                {{ submission.student }}</td>
                                <td>
                                    <input type="number" required name="marks_{{ submission.id }}" value="{{ submission.marks }}">
                                </td>
                                <td>{{ submission.submitted_at }}</td>
                                <td><button class="btn-info" data-report="{{ submission.ai_report }}">AI Grader Report</button></td>
                                <td>{{submission.ai_marks}}</td>
                            <td><a href="{{ submission.submission.url }}" target="_blank">Download</a></td>

                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit">Update Marks</button>
        </form>
    {% else %}
        <p>No uploads yet by the students.</p>
    {% endif %}
</div>

<!-- Modal Structure -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <div id="modal-report" class="modal-text"></div>
    </div>
</div>

<script>
 function getCSRFToken() {
        var csrfToken = null;
        var cookieList = document.cookie.split(';');
        for (var i = 0; i < cookieList.length; i++) {
            var cookieParts = cookieList[i].trim().split('=');
            if (cookieParts[0] === 'csrftoken') {
                csrfToken = decodeURIComponent(cookieParts[1]);
                break;
            }
        }
        return csrfToken;
    }

        
    $('.btn-info').on('click', function () {
        event.preventDefault(); // Prevent the default form submission behavior

        var aiReport = $(this).data('report');
        // Replace text wrapped inside ** with <strong> tags
        aiReport = aiReport.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
        $('#modal-report').html('<p>' + aiReport + '</p>');
        $('#myModal').css('display', 'block');
    });

    // Close the modal when the close button or outside the modal is clicked
    $('.close').on('click', function () {
        $('#myModal').css('display', 'none');
    });

    $(window).on('click', function (event) {
        if (event.target == $('#myModal')[0]) {
            $('#myModal').css('display', 'none');
        }
    });
</script>

<style>
    /* CSS for the modal */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }

    /* Close Button */
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    /* Style for the modal text */
    .modal-text {
        /* Add styles similar to the rest of the page */
        font-family: Arial, sans-serif;
        font-size: 14px;
        line-height: 1.6;
        color: #333;
    }
    
</style>

app/templates/app/room/assignments.html
{% load static %}
<link rel="stylesheet" href="{% static 'app/timepicker/jquery.timepicker.min.css' %}">
<script src="{% static 'app/timepicker/jquery.timepicker.min.js' %}"></script>
<div class="assignments-container">

<h1>Assignments</h1><br>

{% if user.is_teacher %}
<!-- Display assignments for teacher -->
<form method="post" action="{% url 'app:room_assignments' room_id=room.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Conduct Assignment</button>
</form>
{% if assignments %}
<br>
    <h1>Your Conducted Assignments</h1>
    <br>
<table class="table">
    <thead>
        <tr>
            <th>Assignment Title</th>
            <th>Total Marks</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for assignment in assignments %}
            <tr>
                <td>{{ assignment.title }}</td>
                <td>{{ assignment.total_marks }}</td>
                {% if user.is_teacher %}
                    <td>
                        <a href="/{{assignment.file.document}}" target="_blank">See assignment</a>
                        <a class="load-assignment-submissions" data-assignment-id="{{ assignment.id }}" href="#">See Submissions</a>

                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No assignments available.</p>
{% endif %}
{% else %}
    <!-- Display assignments for student -->
    {% if assignments %}
        <table class="table">
            <thead>
                <tr>
                    <th>Assignment Title</th>
                    <th>End Time</th>
                    <th>Created at:</th>
                    <th>Action</th>
                    <th>Download</th>

                </tr>
            </thead>
            <tbody>
                {% for assignment in assignments %}
                    <tr>
                        <td>{{ assignment.title }}</td>
                        <td>{{ assignment.end_time }}</td>
                        <td>{{ assignment.created_at }}</td>
                        <td>
                            <form method="post" action="{% url 'app:room_assignments' room_id=room.id %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="assignment_id" value="{{ assignment.id }}">
                                <input type="hidden" name="document" value="{{ assignment.file.document }}">

                                {% if assignment.id not in submitted_assignment_ids %}
                                    {{ form.as_p }}
                                    <button type="submit">Submit</button>
                                {% else %}
                                    <p>Assignment submitted</p>
                                {% endif %}
                                <div class="upload-instruction">
                                    <i class="fas fa-info-circle"></i>
                                    <p>Upload only submissions only in .pdf extension.</p>
                                  </div>
                            </form>
                        </td>
                        <td><a href="/{{assignment.file.document}}" target="_blank">See Assignment</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No assignments available.</p>
    {% endif %}
{% endif %}
</div>
<div id="submission-container"></div>

<script>
     $(document).ready(function() {
        $('#id_end_time').timepicker({});
    
        $('.load-assignment-submissions').click(function(e) {
            e.preventDefault();
            var assignmentID = $(this).data('assignment-id');
            $.ajax({
                url: "{% url 'app:submitted_assignments' assignment_id=0 %}".replace('0', assignmentID),
                type: "GET",
                success: function(response) {
                    $('#submission-container').html(response);
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
    
        $('.assignments-container').css('opacity', '0').animate({ opacity: '1' }, 300);
    });

</script>

app/templates/app/room/exam_submissions.html
<!-- app/room/exam_submissions.html -->
<div id="exam-result-container"></div>

<div class="exams-container">
    <h2>Submissions for <b>{{ exam.title }}</b></h2>
    {% if submissions %}
        <form method="post" action="{% url 'app:update_exam_submission_marks' exam_id=exam.id %}">
            {% csrf_token %}
            <table class="table">
                <thead>
                    <tr>
                        
                        <th>Student</th>
                        <th>Marks</th>
                        <th>Submitted At</th>
                        <th>AI Report</th>
                        <th>AI Marks</th>
                        <th>Submission</th>
                    </tr>
                </thead>
                <tbody>
                    {% for submission in submissions %}
                        <tr>
                            <td>
                                {% load static %}
                                {% if submission.student.profile_picture %} 
                                <img style="border-radius: 50%;" src="http://127.0.0.1:8000/{{ submission.student.profile_picture }}" alt="Profile Picture">
                                 {% else %}
                               <!-- Default profile picture if user doesn't have one --> <img style="border-radius: 50%;"
                                 src="{% static 'app/default.jpg' %}" alt="">
                                  {% endif %}
                                  {{ submission.student }}
                            </td>
                            <td>
                                <input type="number" required name="marks_{{ submission.id }}" value="{{ submission.marks }}">
                            </td>
                            <td>{{ submission.submitted_at }}</td>
                            <td><button class="btn-info" data-report="{{ submission.ai_report }}">AI Grader Report</button></td>
                            <td>{{submission.ai_marks}}</td>

                            <td>
                                <a href="{{ submission.submission.url }}" target="_blank">Download</a></td>
                            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit">Update Marks</button> 
        </form>
    {% else %}
        <p>No uploads yet by the students.</p>
    {% endif %}
</div>

<!-- Modal Structure -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <div id="modal-report" class="modal-text"></div>
    </div>
</div>


<script>
 function getCSRFToken() {
        var csrfToken = null;
        var cookieList = document.cookie.split(';');
        for (var i = 0; i < cookieList.length; i++) {
            var cookieParts = cookieList[i].trim().split('=');
            if (cookieParts[0] === 'csrftoken') {
                csrfToken = decodeURIComponent(cookieParts[1]);
                break;
            }
        }
        return csrfToken;
    }

        
    $('.btn-info').on('click', function () {
        event.preventDefault(); // Prevent the default form submission behavior

        var aiReport = $(this).data('report');
        // Replace text wrapped inside ** with <strong> tags
        aiReport = aiReport.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
        $('#modal-report').html('<p>' + aiReport + '</p>');
        $('#myModal').css('display', 'block');
    });

    // Close the modal when the close button or outside the modal is clicked
    $('.close').on('click', function () {
        $('#myModal').css('display', 'none');
    });

    $(window).on('click', function (event) {
        if (event.target == $('#myModal')[0]) {
            $('#myModal').css('display', 'none');
        }
    });
</script>

<style>
    /* CSS for the modal */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }

    /* Close Button */
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    /* Style for the modal text */
    .modal-text {
        /* Add styles similar to the rest of the page */
        font-family: Arial, sans-serif;
        font-size: 14px;
        line-height: 1.6;
        color: #333;
    }
</style>

app/templates/app/room/exams.html
{% load static %}
<link rel="stylesheet" href="{% static 'app/timepicker/jquery.timepicker.min.css' %}">
<script src="{% static 'app/timepicker/jquery.timepicker.min.js' %}"></script>
<div class="exams-container">

<h1>Exams</h1><br>

{% if user.is_teacher %}
<!-- Display exams for teacher -->
<form method="post" action="{% url 'app:room_exams' room_id=room.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Conduct Exam</button>
</form>
<br>
    <h1>Your Conducted Exams</h1>
    <br>
{% if exams %}
<table class="table">
    <thead>
        <tr>
            <th>Exam Title</th>
            <th>Exam started at:</th>
            <th>Total Marks</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for exam in exams %}
            <tr>
                <td>{{ exam.title }}</td>
                <td>{{ exam.created_at }}</td>
                <td>{{ exam.total_marks }}</td>
                {% if user.is_teacher %}
                    <td>
                        <a href="/{{exam.file.document}}" target="_blank">See Exam</a>
                        <a class="load-exam-submissions" data-exam-id="{{ exam.id }}" href="#">See Submissions</a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No Exam available.</p>
{% endif %}
{% else %}
    <!-- Display quizzes for student -->
    {% if exams %}
        <table class="table">
            <thead>
                <tr>
                    <th>Exam Title</th>
                    <th>End Time</th>
                    <th>Created at:</th>
                    <th>Action</th>
                    <th>Download</th>

                </tr>
            </thead>
            <tbody>
                {% for exam in exams %}
                    <tr>
                        <td>{{ exam.title }}</td>
                        <td>{{ exam.end_time }}</td>
                        <td>{{ exam.created_at }}</td>
                        <td>
                            <form method="post" action="{% url 'app:room_exams' room_id=room.id %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="exam_id" value="{{ exam.id }}">
                                <input type="hidden" name="document" value="{{ exam.file.document }}">

                                {% if exam.id not in submitted_exam_ids %}
                                    {{ form.as_p }}
                                    <button type="submit">Submit</button>
                                {% else %}
                                    <p>Exam submitted</p>
                                {% endif %}
                                <div class="upload-instruction">
                                    <i class="fas fa-info-circle"></i>
                                    <p>Upload only submissions only in .pdf extension.</p>
                                  </div>
                            </form>
                        </td>
                        <td><a href="/{{exam.file.document}}" target="_blank">See Exam</a></td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No Exams available.</p>
    {% endif %}
{% endif %}
</div>
<div id="submission-container"></div>


<script>
     $(document).ready(function() {
        $('#id_end_time').timepicker({});
    
        $('.load-exam-submissions').click(function(e) {
            e.preventDefault();
            var examId = $(this).data('exam-id');
            $.ajax({
                url: "{% url 'app:submitted_exams' exam_id=0 %}".replace('0', examId),
                type: "GET",
                success: function(response) {
                    $('#submission-container').html(response);
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
    });

    $(document).ready(function(){
$('#id_end_time').timepicker({});
    });
</script>

app/templates/app/room/quizzes.html
<!-- quizzes.html -->
{% load static %}
<link rel="stylesheet" href="{% static 'app/timepicker/jquery.timepicker.min.css' %}">
<script src="{% static 'app/timepicker/jquery.timepicker.min.js' %}"></script>
<div class="quizzes-container">
    <h1>Quizzes</h1><br>

    {% if user.is_teacher %}
        <!-- Display quizzes for teacher -->
        <form method="post" action="{% url 'app:room_quizzes' room_id=room.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Conduct Quiz</button>
        </form>
    {% if quizzes %}
    <br>
    <h1>Your Conducted Quizzes</h1>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Quiz Title</th>
                <th>Quiz started at:</th>
                <th>Total Marks</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in quizzes %}
                <tr>
                    <td>{{ quiz.title }}</td>
                    <td>{{ quiz.created_at }}</td>
                    <td>{{ quiz.total_marks }}</td>
                    {% if user.is_teacher %}
                        <td>
                            <a href="/{{quiz.file.document}}" target="_blank">See Quiz</a>
                            <a class="load-quiz-submissions" data-quiz-id="{{ quiz.id }}" href="#">See Submissions</a>

                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No quizzes available.</p>
{% endif %}
    {% else %}
        <!-- Display quizzes for student -->
        {% if quizzes %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Quiz Title</th>
                        <th>End Time</th>
                        <th>Created at:</th>
                        <th>Action</th>    
                        <th>Download</th>
    
                        
                    </tr>
                </thead>
                <tbody>
                    {% for quiz in quizzes %}
                        <tr>
                            <td>{{ quiz.title }}</td>
                            <td>{{ quiz.end_time }}</td>
                            <td>{{ quiz.created_at }}</td>
                            <td>
                                <form method="post" action="{% url 'app:room_quizzes' room_id=room.id %}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="quiz_id" value="{{ quiz.id }}">
                                    <input type="hidden" name="document" value="{{ quiz.file.document }}">
                                    {% if quiz.id not in submitted_quiz_ids %}
                                        {{ form.as_p }}
                                        <button type="submit">Submit</button>
                                    {% else %}
                                        <p>Quiz submitted</p>
                                    {% endif %}
                                    <div class="upload-instruction">
                                        <i class="fas fa-info-circle"></i>
                                        <p>Upload only submissions only in .pdf extension.</p>
                                      </div>
                                </form>
                                
                            </td>
                            <td><a href="/{{quiz.file.document}}" target="_blank">See Quiz</a></td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        {% else %}
            <p>No quizzes available.</p>
        {% endif %}
    {% endif %}
</div>
<div id="submission-container"></div>
<script>
    $(document).ready(function() {
        $('#id_end_time').timepicker({});
    
        $('.load-quiz-submissions').click(function(e) {
            e.preventDefault();
            var quizId = $(this).data('quiz-id');
            $.ajax({
                url: "{% url 'app:submitted_quizzes' quiz_id=0 %}".replace('0', quizId),
                type: "GET",
                success: function(response) {
                    $('#submission-container').html(response);
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
    });

    $(document).ready(function () {
        $('.quizzes-container').css('opacity', '0').animate({ opacity: '1' }, 300);

    });
    </script>
    