app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from app import views

app_name = 'app'  # Add this line to specify the app namespace


urlpatterns = [
    path("",views.home, name='home'),
    path('create-room/', views.create_room, name='create_room'),
    path('join-room/', views.join_room, name='join_room'),
    path('joined-rooms/',views.joined_rooms,name='joined_rooms'),
    path('leave-room/<int:room_id>/', views.leave_room, name='leave_room'),
    path('created-rooms/', views.created_rooms, name='created_rooms'),
    path('room/<int:room_id>/delete/', views.delete_room, name='delete_room'),

    path('room/<int:room_id>/quizzes', views.room_quizzes, name='room_quizzes'),
    path('room/<int:room_id>/assignments/', views.room_assignments, name='room_assignments'),
    path('room/<int:room_id>/exams/', views.room_exams, name='room_exams'),

    path('quiz/<int:quiz_id>/submit/', views.room_quizzes, name='submit_quiz'),
    path('assignment/<int:assignment_id>/submit/', views.room_assignments, name='submit_assignment'),
    path('exam/<int:exam_id>/submit/', views.room_exams, name='submit_exam'),
    
    path('submissions/quizzes/<int:quiz_id>/', views.submitted_quizzes, name='submitted_quizzes'),
    path('submissions/assignments/<int:assignment_id>/', views.submitted_assignments, name='submitted_assignments'),
    path('submissions/exams/<int:exam_id>/', views.submitted_exams, name='submitted_exams'),


    path('update_submission_marks/<int:quiz_id>/', views.update_quiz_submission_marks, name='update_quiz_submission_marks'),
    path('update_assignment_submission_marks/<int:assignment_id>/', views.update_assignment_submission_marks, name='update_assignment_submission_marks'),
    path('update_exam_submission_marks/<int:exam_id>/', views.update_exam_submission_marks, name='update_exam_submission_marks'),
    
    path('check-submission/', views.check_submission, name='check_submission'),

    path('kick_participant/<int:room_id>/<int:user_id>/', views.kick_participant, name='kick_participant'),
    path('room/<int:room_id>/participants/', views.load_participants, name='load_participants'),


    path('student-analytics/', views.student_analytics, name='student_analytics'),
    path('teacher-analytics/', views.teacher_analytics, name='teacher_analytics'),

    path('room_detail/<int:room_id>/', views.room_detail, name='room_detail'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
    path('room/<int:room_id>/join-requests/', views.join_requests, name='join_requests'),
    path('accept-join-request/<int:room_id>/<int:user_id>/', views.accept_join_request, name='accept_join_request'),
    path('reject-join-request/<int:room_id>/<int:user_id>/', views.reject_join_request, name='reject_join_request'),
    path('upload-book/', views.upload_book, name='upload_book'),
    path('book-list/', views.book_list, name='book_list'),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('query-form/', views.process_query1, name='query_form'),
    path('save-pdf/', views.save_pdf, name='save_pdf'),
    path('created_docs/', views.created_docs, name='created_docs'),
    path('delete_document/<int:doc_id>/', views.delete_document, name='delete_document'),

    path('help/',views.help, name='help'),


]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fyp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('', include('app.urls', namespace='app')),  # Include 'app/urls.py' with the namespace taa kay hum login k bad redirect krskyn
]

app/templates/app/book_list.html
{% extends 'base.html' %}

{% block content %}
<div class="dashboard-container">

    {% load static %}
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <h2>Your Uploaded Books</h2>
    <div class="books-container">
        {% if uploaded_books.all %}
        {% for book in uploaded_books.all %}
            <div class="card">
                <h3 class="book-title">{{ book.title }}</h3>
                <p class="upload-date">Uploaded on: {{ book.uploaded_at }}</p>
                <div class="button-group">
                    <form method="GET" action="{% url 'app:book_detail' book.id %}">
                        <button class="view-button" type="submit">View Book</button>
                    </form>
                    <form method="POST" action="{% url 'app:delete_book' book.id %}">
                        {% csrf_token %}
                        <button class="delete-button" type="submit">Delete Book</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        {% else %}
        <p class="no-books">You have no uploaded books.</p>
        {% endif %}
    </div>
    <div style="padding: 20px;">
    <a class="btn btn-primary" href="{% url 'app:upload_book' %}">Upload a Book</a>
</div>
</div>

<script>
    $(document).ready(function() {
      $('.dashboard-container').css('opacity', '0').animate({ opacity: '1' }, 300);
    });
</script>

<style>

  .dashboard-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    padding: 20px;
  }

  .card {
    font-size: 34px;
    padding: 22px;
    min-width: 200px;
    /* Minimum width of each card */
    background-size: cover;
    /* Stretch the background image to cover the entire card */
    background-position: center;
    /* Center the background image */
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: .5em;

    transform-style: preserve-3d; /* Preserve 3D transformations */

    height: 200px;
    /* Fixed height for cards */
    background-image: url("{% static 'app/book.jpg' %}");
    background-size: cover;
    /* Stretch the background image to cover the entire card */
    background-position: center;
    /* Center the background image */
    display: flex;
    transform:
    perspective(800px)
    rotateY(-8deg);
  transition: transform 1s ease 0s;
  border-radius: 4px;
  box-shadow:
    rgba(0, 0, 0, 0.024) 0px 0px 0px 1px,
    rgba(0, 0, 0, 0.05) 0px 1px 0px 0px,
    rgba(0, 0, 0, 0.03) 0px 0px 8px 0px,
    rgba(0, 0, 0, 0.1) 0px 20px 30px 0px;

  &:hover {
    transform: perspective(800px) rotateY(-4deg);
  }
    
  }

.card .book-title{
  font-weight: bold;

}
  .upload-date {
    font-size: 24px;
  }

  .book-title,
  .upload-date {
    color: rgb(0, 0, 0);
  }

  a {
    text-decoration: none;

  }

  .card i {
    filter: invert(100);
  }
 
</style>
{% endblock %}

app/templates/app/created_rooms.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <div class="dashboard-container">
        <h3>Your Created Rooms</h3>
        {% if created_rooms %}
            <div class="books-container">
                {% for room in created_rooms %}
                    <div class="card">
                        <h3 class="room-title">{{ room.name }}</h3>
                        <div class="button-group">
                            <a href="{% url 'app:room_detail' room_id=room.id %}" class="view-button"><i class="fas fa-portal-enter"></i>Enter Room</a>
                            <form method="POST" action="{% url 'app:delete_room' room.id %}">
                                {% csrf_token %}
                                <button class="delete-button" type="submit"><i class="fa-solid fa-trash-can" style="margin-right: 2px;"></i>Delete Room</button>
                            </form>                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="no-books">You haven't created any rooms yet.</p>
        {% endif %}

        <a href="{% url 'app:create_room' %}" class="btn btn-primary">Create Rooms</a>
        <a href="{% url 'app:home' %}" class="btn btn-primary">Go Back</a>
    </div>


    <script>
      $(document).ready(function() {
        $('.dashboard-container').css('opacity', '0').animate({ opacity: '1' }, 300);
      });
    </script>

    <style>
        .dashboard-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    padding: 20px;
  }
  .card {
    font-size: 34px;
    padding: 22px;
    min-width: 200px;
    /* Minimum width of each card */
    background-size: cover;
    /* Stretch the background image to cover the entire card */
    background-position: center;
    /* Center the background image */
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: .5em;

    transform-style: preserve-3d; /* Preserve 3D transformations */

    height: 200px;
    /* Fixed height for cards */
    background-image: url("{% static 'app/bg.jpg' %}");
    background-size: cover;
    /* Stretch the background image to cover the entire card */
    background-position: center;
    /* Center the background image */
    display: flex;
    transform:
    perspective(800px)
    rotateY(-8deg);
  transition: transform 1s ease 0s;
  border-radius: 4px;
  box-shadow:
    rgba(0, 0, 0, 0.024) 0px 0px 0px 1px,
    rgba(0, 0, 0, 0.05) 0px 1px 0px 0px,
    rgba(0, 0, 0, 0.03) 0px 0px 8px 0px,
    rgba(0, 0, 0, 0.1) 0px 20px 30px 0px;

  &:hover {
    transform: perspective(800px) rotateY(-4deg);
  }
    
  }
  

.card .room-title{
  font-weight: bold;

}
  .room-title {
    font-size: 24px;
  }

  .room-title {
    color: white;
  }

  a {
    text-decoration: none;

  }

  .card i {
    filter: invert(100);
  }
  .fa-portal-enter i {
    filter: invert(100);
}
 
    </style>
{% endblock %}

app/templates/app/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'app/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
<div class="row">
  <div class="card1">
      <h4>Dashboard</h4>
  </div>
  
</div>
<div class="dashboard-container">
  {% if user.is_teacher %}
  <a href="{% url 'app:created_rooms' %}">
    <div class="card">
      <div class="front">
        <i class="fa-solid fa-door-open"></i>
        <div class="label">Rooms</div>
      </div>
      <div class="back">
        <div class="description">
          Manage created rooms.
        </div>
      </div>
    </div>
  </a>
  <a href="{% url 'app:book_list' %}">
    <div class="card">
      <div class="front">
        <i class="fa-solid fa-robot"></i>
        <div class="label">AI Generation</div>
      </div>
      <div class="back">
        <div class="description">
          View and manage AI-generated content.
        </div>
      </div>
    </div>

  </a>
  <a href="{% url 'app:teacher_analytics' %}">
    <div class="card">
      <div class="front">
        <i class="fa-solid fa-chart-line"></i>
        <div class="label">See Analytics</div>
      </div>
      <div class="back">
        <div class="description">
          View analytics related to your teaching activities.
        </div>
      </div>

    </div>
  </a>

  <a href="{% url 'app:created_docs' %}">
    <div class="card">
      <div class="front">
        <i class="fas fa-save"></i>
        <div class="label">Saved Generations</div>
      </div>
      <div class="back">
        <div class="description">
          Manage your AI documents.
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'app:help' %}">
    <div class="card">
      <div class="front">
        <i class="fa-regular fa-circle-question"></i>
        <div class="label">Help?</div>
      </div>
      <div class="back">
        <div class="description">
          Get help and support.
        </div>
      </div>
    </div>
  </a>
  

  {% else %}

  <a href="{% url 'app:joined_rooms' %}">
    <div class="card">
      <div class="front">
        <i class="fa-solid fa-door-open"></i>
        <div class="label">Rooms</div>
      </div>
      <div class="back">
        <div class="description">
          View joined rooms.
        </div>
      </div>
    </div>

  </a>
  <a href="{% url 'app:student_analytics' %}">
    <div class="card">
      <div class="front">
        <i class="fa-solid fa-chart-line"></i>
        <div class="label">See Analytics</div>
      </div>
      <div class="back">
        <div class="description">
          View analytics related to your learning activities.
        </div>
      </div>
    </div>
  </a><br>
  <a href="{% url 'app:help' %}">
    <div class="card">
      <div class="front">
        <i class="fa-regular fa-circle-question"></i>
        <div class="label">Help?</div>
      </div>
      <div class="back">
        <div class="description">
          Get help and support.
        </div>
      </div>
    </div>
  </a>
  
</div>

{% endif %}


<script>
  $(document).ready(function () {
    $('.dashboard-container').css('opacity', '0').animate({ opacity: '1' }, 300);
  });
</script>
<style>
.dashboard-container {
    display: flex;
    flex-wrap: wrap;
    flex-direction: row;
    justify-content: center;
    gap: 40px;
    padding: 40px;
    background-image: linear-gradient(to bottom right, #9ae3d8, #c8bdbd); /* Gradient background */
    transition: filter 2s ease; /* Smooth transition effect for filter */
}


.dashboard-container:not(:hover) {
    filter: invert(0%); /* Revert filter to original state */
    cursor: auto; /* Revert cursor to default state */
}

  .card {
    font-size: 34px;
    padding: 22px;
    min-width: 200px;
    /* Minimum width of each card */
    background-size: cover;
    /* Stretch the background image to cover the entire card */
    background-position: center;
    /* Center the background image */
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: .5em;

    transform-style: preserve-3d; /* Preserve 3D transformations */

    height: 200px;
    /* Fixed height for cards */
    background-image: url("{% static 'app/bg.jpg' %}");
    background-size: cover;
    /* Stretch the background image to cover the entire card */
    background-position: center;
    /* Center the background image */
    display: flex;
    transform:
    perspective(800px)
    rotateY(-8deg);
  transition: transform 1s ease 0s;
  border-radius: 4px;
  box-shadow:
    rgba(0, 0, 0, 0.024) 0px 0px 0px 1px,
    rgba(0, 0, 0, 0.05) 0px 1px 0px 0px,
    rgba(0, 0, 0, 0.03) 0px 0px 8px 0px,
    rgba(0, 0, 0, 0.1) 0px 20px 30px 0px;

  &:hover {
    transform: perspective(800px) rotateY(-4deg);
  }
    
  }

.card .label{
  font-weight: bold;

}
  .description {
    font-size: 24px;
  }

  .description,
  .label {
    color: white;
  }

  a {
    text-decoration: none;

  }

  .card i {
    filter: invert(100);
  }
 
</style>
{% endblock %}

app/templates/app/join_req.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
    <div class="dashboard-container join-requests-container">
        <h2>Join Requests for Room: {{ room.name }}</h2>
        {% if user.is_teacher %}
            {% if join_requests %}
                <ul class="join-requests-list">
                    {% for join_request in join_requests %}
                        <li id="join-request-{{ join_request.id }}">
                            {{ join_request.username }} - {{ join_request.email }} - {{ join_request.date_joined }}
                            <form method="post" action="{% url 'app:accept_join_request' room_id=room.id user_id=join_request.id %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="accept-btn">Accept</button>
                            </form>
                            <form method="post" action="{% url 'app:reject_join_request' room_id=room.id user_id=join_request.id %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="reject-btn">Reject</button>
                            </form>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No join requests for this room.</p>
            {% endif %}
        {% else %}
            <p>You are not authorized to view join requests.</p>
        {% endif %}
        <a href="{% url 'app:room_detail' room_id=room.id %}" class="dashboard-btn">Go Back</a>
    </div>

    <script>
        $(document).ready(function() {
            $('.dashboard-container').css('opacity', '0').animate({ opacity: '1' }, 300);

        
        });
    </script>
{% endblock %}

app/templates/app/join_room.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    
    <div class="join-room-container">
        {% if not user.is_teacher %}
            <h2>Join a Room</h2>
            
            <form id="join-room-form" method="post" action="{% url 'app:join_room' %}">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="{{ form.room_name.id_for_label }}">Room Name:</label>
                    {{ form.room_name }}
                    <i>{{ form.room_name.errors }}</i>
                </div>
                
                <div class="form-group">
                    <label for="{{ form.pass_key.id_for_label }}">Pass Key:</label>
                    {{ form.pass_key }}
                    <i>{{ form.pass_key.errors }}</i>
                </div>
                
                <button style="margin-left: 45%;" class="join-room-btn">Send Request</button>
            </form>

            <div id="join-room-modal" class="modal">
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <p id="modal-message"></p>
                </div>
            </div>
            
        {% else %}
            <p class="teacher-message">Teachers cannot join a room.</p>
        {% endif %}
        
        <a href="{% url 'app:home' %}" class="dashboard-btn">Go Home</a>
    </div>

    <script>
        $(document).ready(function() {
            $('.join-room-container').css('opacity', '0').animate({ opacity: '1' }, 300);
        });

        // Modal script
        var modal = document.getElementById("join-room-modal");
        var span = document.getElementsByClassName("close")[0];

        $('#join-room-form').submit(function(event) {
            event.preventDefault(); // Prevent form submission

            $.ajax({
                type: "POST",
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(response) {
                    // Update modal content with JSON response
                    $('#modal-message').text(response.message);
                    modal.style.display = "block"; // Show modal
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });

        // Close modal when the user clicks on <span> (x)
        span.onclick = function() {
            modal.style.display = "none";
        };

        // Close modal when the user clicks anywhere outside of the modal
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        };
    </script>
{% endblock %}

app/templates/app/joined_rooms.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'app/style.css' %}">
<div class="dashboard-container">
    <h4>Your Joined Rooms:</h4>
    {% if joined_rooms %}
    <div class="books-container">
        {% for room in joined_rooms %}
        <div class="card">
            <h3 class="room-title">{{ room.name }}</h3>
            <div class="button-group">
                <a href="{% url 'app:room_detail' room_id=room.id %}" class="view-button">Go to Room</a>
                <form method="POST" action="{% url 'app:delete_room' room.id %}">
                    {% csrf_token %}
                    <button class="delete-button" type="submit">
                        <i class="fas fa-door-open" style="margin-right: 5px;"></i>
                        Leave Room
                    </button>             
                   </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p class="no-books">You haven't joined any rooms yet.</p>
        {% endif %}
        <form method="post" action="{% url 'app:join_room' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="dashboard-btn">Join a Room</button>
        </form>
    </div>


    <style>
        .dashboard-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 20px;
            padding: 20px;
        }

        .card {
            position: relative;
            /* Make the card position relative for absolute positioning of Room.svg */

            font-size: 34px;
            padding: 22px;
            min-width: 200px;
            /* Minimum width of each card */
            background-size: cover;
            /* Stretch the background image to cover the entire card */
            background-position: center;
            /* Center the background image */
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: .5em;

            transform-style: preserve-3d;
            /* Preserve 3D transformations */

            height: 200px;
            /* Fixed height for cards */
            background-image: url("{% static 'app/bg.jpg' %}");
            /* Stretch the background image to cover the entire card */
            background-position: center;
            /* Center the background image */
            display: flex;
            transform:
                perspective(800px) rotateY(-8deg);
            transition: transform 1s ease 0s;
            border-radius: 4px;
            box-shadow:
                rgba(0, 0, 0, 0.024) 0px 0px 0px 1px,
                rgba(0, 0, 0, 0.05) 0px 1px 0px 0px,
                rgba(0, 0, 0, 0.03) 0px 0px 8px 0px,
                rgba(0, 0, 0, 0.1) 0px 20px 30px 0px;

            &:hover {
                transform: perspective(800px) rotateY(-4deg);
            }

            .card::before {
                content: "";
                /* Create a pseudo-element for absolute positioning of Room.svg */
                position: absolute;
                bottom: 0;
                /* Position at the bottom */
                left: 0;
                /* Position at the left */
                background-image: url("{% static 'app/bg.jpg' %}");
                width: 50px;
                /* Adjust width as needed */
                height: 50px;
                /* Adjust height as needed */
            }


        }

        .view-btn {
            display: inline-block;
            padding: 10px 20px;
            border-radius: 10px;
            /* Make the button round */
            background-color: #007bff;
            /* Button background color */
            color: white;
            /* Button text color */
            text-decoration: none;
            transition: background-color 0.3s ease;
            /* Add transition for hover effect */
        }

        .view-btn:hover {
            background-color: #0056b3;
            /* Change background color on hover */
        }

        .card .room-title {
            font-weight: bold;

        }

        .room-title {
            font-size: 24px;
        }

        .room-title {
            color: rgb(255, 255, 255);
        }

        a {
            text-decoration: none;

        }

        .card i {
            filter: invert(100);
        }
        .delete-button {
    background-color: #ca0d20; /* Light Red */
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s;
}

.delete-button:hover {
    background-color: #e57373; /* Darker shade of red on hover */
}

    </style>
    {% endblock %}

app/templates/app/room_detail1.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">

{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="row">
    <div class="card1">
        <h4>Room Detail</h4>
    </div>
    <div class="room-detail-container">
        <div style="display: grid; justify-content: center; font-size: larger;">
            <h2>{{ room.name }}</h2>
            <hr>
            <p>Room Owner: <img style="border-radius: 50%; margin-right: 2px;" src="http://34.125.209.178:8090/{{ room.creator.profile_picture }}" alt="Profile Picture">{{room.creator.username }}</p>
            <p>Total Joined Students: {{ room.participants.count }}</p>
            <p>PassKey: <i style="color: tomato;">{{ room.pass_key }}</i></p>
        </div>

        <!-- Display links for teacher -->
        <div class="teacher-links">
            <button id="load-quizzes" class="btn btn-primary"><i class="fa-solid fa-person-chalkboard"></i>
                Quizzes</button>
            <button id="load-assignments" class="btn btn-primary"><i class="fa-solid fa-book-open"></i>
                Assignments</button>
            <button id="load-exams" class="btn btn-primary"><i class="fa-solid fa-graduation-cap"></i> Exams</button>
            {% if user.is_teacher %}
            <a href="{% url 'app:join_requests' room_id=room.id %}">
                <button class="btn btn-info">
                    See Join Requests
                    <!-- Add a badge with the count of join requests -->
                    <span class="badge badge-pill badge-danger" id="join-requests-badge">{{room.join_requests.count}}</span>
                </button>
            </a>
            <a href="#" id="see-participants-btn" data-room-id="{{ room.id }}">
                <button class="btn btn-success">See Participants</button>
            </a>
            <div id="participants-container"></div>
            {% endif %}
        </div>

        <!-- Create a div to hold the loaded content -->
        <div id="content-container"></div>

    </div>

    <script>

        $(document).ready(function () {
            // Attach click event handlers to load quizzes
            $("#load-quizzes").click(function () {
                loadContent("{% url 'app:room_quizzes' room_id=room.id %}");
            });

            // Attach click event handlers to load assignments
            $("#load-assignments").click(function () {
                loadContent("{% url 'app:room_assignments' room_id=room.id %}");
            });

            // Attach click event handlers to load exams
            $("#load-exams").click(function () {
                loadContent("{% url 'app:room_exams' room_id=room.id %}");
            });

            // Attach click event handlers to load Participants
            $("#see-participants-btn").click(function () {
                loadContent("{% url 'app:load_participants' room_id=room.id %}");
            });


            // Function to load content using AJAX
            function loadContent(url) {
                $.ajax({
                    url: url,
                    type: "GET",
                    success: function (response) {
                        // Insert the fetched content into the content container
                        $("#content-container").html(response);
                    },
                    error: function (xhr, errmsg, err) {
                        console.log(errmsg);
                    }
                });
            }
        });



    </script>

    <style>
        form {
            padding: 20px;
            /* Add some padding */
            border: 1px solid #ccc;
            /* Add a border */
            border-radius: 8px;
            /* Add some border radius for rounded corners */
            background-color: #f9f9f9;
            /* Add a light background color */
        }

        /* Style for form inputs */
        form input[type="text"],
        form input[type="number"],
        form textarea , 
    form select {
            width: 100%;
            /* Take up full width */
            padding: 10px;
            /* Add padding */
            margin-bottom: 10px;
            /* Add some space between inputs */
            border: 1px solid #ccc;
            /* Add a border */
            border-radius: 4px;
            /* Add some border radius for rounded corners */
            box-sizing: border-box;
            /* Include padding and border in element's total width and height */
        }

        /* Style for the submit button */
        form input[type="submit"] {
            width: 100%;
            /* Take up full width */
            padding: 10px;
            /* Add padding */
            background-color: #007bff;
            /* Set background color */
            color: #fff;
            /* Set text color */
            border: none;
            /* Remove border */
            border-radius: 4px;
            /* Add some border radius for rounded corners */
            cursor: pointer;
            /* Add pointer cursor on hover */
        }

        /* Style for form field labels */
        form label {
            font-weight: bold;
            /* Make labels bold */
        }

        .upload-instruction {
            background-color: #ffffcc;
            /* Yellow background color */
            border-radius: 10px;
            /* Rounded corners */
            padding: 10px;
            /* Padding around the content */
            display: flex;
            /* Display flex to align items */
            align-items: center;
            /* Center items vertically */
            max-width: 100%;
            /* Set maximum width */
        }

        .upload-instruction i {
            color: #d6c16c;
            /* Yellow icon color */
            font-size: 24px;
            /* Icon size */
            margin-right: 10px;
            /* Margin between icon and text */
        }

        .upload-instruction p {
            margin: 0;
            /* Remove default margin */
            font-size: 18px;
            /* Font size */
            color: #333;
            /* Text color */
        }
        h1 {
    font-size: 24px; /* Adjust the font size */
    color: #ff69b4; /* Pink color */
    text-align: center; /* Center the text */
    letter-spacing: 2px; /* Add some letter spacing */
    margin-bottom: 20px; /* Add some space below the heading */
    margin-top: 20px;
    text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.2); /* Add a subtle text shadow */
}
    </style>
    {% endblock %}